"""First migration

Revision ID: 67499f1de378
Revises: f15ea464e1b3
Create Date: 2023-01-19 01:58:54.635504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67499f1de378'
down_revision = 'f15ea464e1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
